spring:
  datasource:
    url: jdbc:postgresql://postgres:5439/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect